### ISSUE TITLE
Add external Cyberpunk iTerm to README

### ISSUE THREAD

**Issue by Murderlon** [max-SS/cyberpunk#55]
Yo Max I really liked your theme so I made an iTerm version of it.
Perhaps it would be nice to add it to your README so people can match editor en terminal ✨
👉 https://github.com/Murderlon/cyberpunk-iterm

**Comment by max-SS** [comment]
WOW 😍... Great idea, thank you very much for showing your support by creating a theme inspired by cyberpunk. Of course I would be happy to add a section in the README that refers to the topic you have created. This weekend I will publish a new version of cyberpunk, and I will take the opportunity to create this section
